# Generated by Django 5.0 on 2024-01-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.comments'),
        ),
    ]
