# Generated by Django 5.0 on 2024-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_text',
            field=models.TextField(null=True),
        ),
    ]
