# Generated by Django 5.0 on 2024-01-26 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='users_who_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
