# Generated by Django 5.0 on 2024-01-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_posts_users_who_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='users_who_liked',
        ),
    ]
