# Generated by Django 4.2.7 on 2024-01-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_posts_likes_posts_liked_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
